### eureka 服务端口号
server:
  port: 8088
### eureka 基本信息配置
spring:
  application:
    name: fh-eureka-server
eureka:
  instance:
    ###注册到eurekaip地址
    hostname: 127.0.0.1
  client:
           #自己是注册中心,所以不需要注册自己
    registerWithEureka: false
           #禁止注册中心拉取注册地址清单
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      

